blank_issues_enabled: true
# contact_links:
#   - name: 📚 Documentation
#     url: https://github.com/learnfromai/nx-starter/blob/master/README.md
#     about: Check the project documentation for setup and usage instructions
#   - name: 💬 Discussions
#     url: https://github.com/learnfromai/nx-starter/discussions
#     about: Ask questions and discuss ideas with the community
