name: E2E Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch: # Allow manual triggering

# Allow concurrent E2E tests per branch
concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

env:
  PNPM_VERSION: '10.13.1'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22] # Use numbers instead of strings for consistency
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Need full history for NX affected analysis

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4 # Updated to v4
      with:
        version: ${{ env.PNPM_VERSION }} # Use updated version
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install Playwright browsers
      run: pnpm exec playwright install --with-deps

    - name: Cache NX cache
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: nx-cache-e2e-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
        restore-keys: |
          nx-cache-e2e-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}-
          nx-cache-e2e-${{ runner.os }}-${{ matrix.node-version }}-
    
    - name: Build libraries first
      run: pnpm run build:libs
    
    - name: Build applications
      run: pnpm run build
    
    - name: Run E2E tests
      run: pnpm run e2e # Fixed command name
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-node-${{ matrix.node-version }}
        path: |
          playwright-report/
          apps/**/playwright-report/
        retention-days: 30
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-node-${{ matrix.node-version }}
        path: |
          test-results/
          apps/**/test-results/
        retention-days: 30

  test-mobile:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION }}
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install Playwright browsers
      run: pnpm exec playwright install --with-deps

    - name: Cache NX cache
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: nx-cache-mobile-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
        restore-keys: |
          nx-cache-mobile-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-
    
    - name: Build libraries and applications
      run: |
        pnpm run build:libs
        pnpm run build
    
    - name: Run Mobile E2E tests
      run: pnpm exec playwright test --project="Mobile Chrome" --project="Mobile Safari" || echo "Mobile tests may not be fully configured yet"
    
    - name: Upload mobile test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-mobile-report
        path: |
          playwright-report/
          apps/**/playwright-report/
        retention-days: 30

  test-cross-browser:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION }}
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install Playwright browsers
      run: pnpm exec playwright install --with-deps

    - name: Cache NX cache
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: nx-cache-cross-browser-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
        restore-keys: |
          nx-cache-cross-browser-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-
    
    - name: Build libraries and applications
      run: |
        pnpm run build:libs
        pnpm run build
    
    - name: Run Cross-browser E2E tests
      run: pnpm exec playwright test --project=chromium --project=firefox --project=webkit || echo "Cross-browser tests may not be fully configured yet"
    
    - name: Upload cross-browser test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-cross-browser-report
        path: |
          playwright-report/
          apps/**/playwright-report/
        retention-days: 30